# <center> HEART DISEASE PREDICTION </center>

Heart disease prediction using two machine learning models.
1. K Nearset Neighbour 
2. ANN Multilayer Perceptron

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook

In [10]:
data = pd.read_csv('https://www.openml.org/data/get_csv/1592290/phpgNaXZe')

In [11]:
column = ['sbp','tobacco','ldl','adiposity','famhist','type','obesity','alcohol','age','chd']

In [12]:
data.columns=column

In [13]:
data.head()

sbp  tobacco   ldl  adiposity  famhist  type  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11        1    49    25.30    97.20   52    2
1  144     0.01  4.41      28.61        2    55    28.87     2.06   63    2
2  118     0.08  3.48      32.28        1    52    29.14     3.81   46    1
3  170     7.50  6.41      38.03        1    51    31.99    24.26   58    2
4  134    13.60  3.50      27.78        1    60    25.99    57.34   49    2

In [14]:
data.describe()

sbp     tobacco         ldl   adiposity     famhist        type  \
count  462.000000  462.000000  462.000000  462.000000  462.000000  462.000000   
mean   138.326840    3.635649    4.740325   25.406732    1.584416   53.103896   
std     20.496317    4.593024    2.070909    7.780699    0.493357    9.817534   
min    101.000000    0.000000    0.980000    6.740000    1.000000   13.000000   
25%    124.000000    0.052500    3.282500   19.775000    1.000000   47.000000   
50%    134.000000    2.000000    4.340000   26.115000    2.000000   53.000000   
75%    148.000000    5.500000    5.790000   31.227500    2.000000   60.000000   
max    218.000000   31.200000   15.330000   42.490000    2.000000   78.000000   

          obesity     alcohol         age         chd  
count  462.000000  462.000000  462.000000  462.000000  
mean    26.044113   17.044394   42.816017    1.346320  
std      4.213680   24.481059   14.608956    0.476313  
min     14.700000    0.000000   15.000000    1.000000  
25%     22.985000    0.510000   31.000000    1.000000  
50%     25.805000    7.510000   45.000000    1.000000  
75%     28.497500   23.892500   55.000000    2.000000  
max     46.580000  147.190000   64.000000    2.000000

Describes the statistical data insights

In [15]:
data.isnull().sum()

sbp          0
tobacco      0
ldl          0
adiposity    0
famhist      0
type         0
obesity      0
alcohol      0
age          0
chd          0
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['famhist']=encoder.fit_transform(data['famhist'])
data['chd']=encoder.fit_transform(data['chd'])

In [17]:
data.head(5)

sbp  tobacco   ldl  adiposity  famhist  type  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11        0    49    25.30    97.20   52    1
1  144     0.01  4.41      28.61        1    55    28.87     2.06   63    1
2  118     0.08  3.48      32.28        0    52    29.14     3.81   46    0
3  170     7.50  6.41      38.03        0    51    31.99    24.26   58    1
4  134    13.60  3.50      27.78        0    60    25.99    57.34   49    1

In [18]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler(feature_range =(0,100))

In [24]:
data['sbp'] = scale.fit_transform(data['sbp'].values.reshape(-1,1))

In [20]:
data.head()

sbp  tobacco   ldl  adiposity  famhist  type  obesity  alcohol  age  \
0  50.427350    12.00  5.73      23.11        0    49    25.30    97.20   52   
1  36.752137     0.01  4.41      28.61        1    55    28.87     2.06   63   
2  14.529915     0.08  3.48      32.28        0    52    29.14     3.81   46   
3  58.974359     7.50  6.41      38.03        0    51    31.99    24.26   58   
4  28.205128    13.60  3.50      27.78        0    60    25.99    57.34   49   

   chd  
0    1  
1    1  
2    0  
3    1  
4    1

In [21]:
data.describe()

sbp     tobacco         ldl   adiposity     famhist        type  \
count  462.000000  462.000000  462.000000  462.000000  462.000000  462.000000   
mean    31.903282    3.635649    4.740325   25.406732    0.584416   53.103896   
std     17.518220    4.593024    2.070909    7.780699    0.493357    9.817534   
min      0.000000    0.000000    0.980000    6.740000    0.000000   13.000000   
25%     19.658120    0.052500    3.282500   19.775000    0.000000   47.000000   
50%     28.205128    2.000000    4.340000   26.115000    1.000000   53.000000   
75%     40.170940    5.500000    5.790000   31.227500    1.000000   60.000000   
max    100.000000   31.200000   15.330000   42.490000    1.000000   78.000000   

          obesity     alcohol         age         chd  
count  462.000000  462.000000  462.000000  462.000000  
mean    26.044113   17.044394   42.816017    0.346320  
std      4.213680   24.481059   14.608956    0.476313  
min     14.700000    0.000000   15.000000    0.000000  
25%     22.985000    0.510000   31.000000    0.000000  
50%     25.805000    7.510000   45.000000    0.000000  
75%     28.497500   23.892500   55.000000    1.000000  
max     46.580000  147.190000   64.000000    1.000000

## MODEL 1 - K Nearest Neighbour

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors =5,n_jobs = -1,leaf_size = 60,algorithm='brute')

In [23]:
knn_clf.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [126]:
y_pred_knn = knn_clf.predict(X_test)
y_pred_knn

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0])

In [127]:
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_knn

array([[49, 11],
       [22, 11]])

In [128]:
knn_result = accuracy_score(y_test,y_pred_knn)
knn_result

0.6451612903225806

## MODEL 2 - ANN Multilayer Perceptron Classifier

In [137]:
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

In [138]:
ann_clf = MLPClassifier()


parameters = {'solver': ['lbfgs'],
             'alpha':[1e-4],
             'hidden_layer_sizes':(9,14,14,2),   
             'random_state': [1]}

In [139]:

acc_scorer = make_scorer(accuracy_score)

 
grid_obj = GridSearchCV(ann_clf, parameters, scoring=acc_scorer)
grid_obj = grid_obj.fit(X_train, y_train)


ann_clf = grid_obj.best_estimator_

In [140]:
ann_clf.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=14, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [141]:
y_pred_ann = ann_clf.predict(X_test)

In [142]:
from sklearn.metrics import confusion_matrix
cm_ann = confusion_matrix(y_test, y_pred_ann)
cm_ann

array([[52,  8],
       [14, 19]])

In [143]:
ann_result = accuracy_score(y_test,y_pred_ann)
ann_result

0.7634408602150538